[package]
name = "ref_monitor"
version = "0.1.0"
edition = "2021"
authors = ["Andrey Khalepov <w54661c@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.29.0"